config/routes.rb
Rails.application.routes.draw do
  resources :members, only: [:create, :show, :index], defaults: {format: :json} do
    post :login, on: :collection
    post :logout, on: :collection
    post :assigned, on: :member
    resources :leave_requests, only: [:create, :show, :index] do
      post :processed, on: :member
    end
    resources :timecards, only: [:create, :show, :index]
    resources :leave_conflicts, only: [:create, :show, :index]
  end

end

app/models/timecard.rb
class Timecard
  include Mongoid::Document
  include Mongoid::Timestamps

  embedded_in :member
  field :hour, type: Integer
  field :date, type: String

  validates_presence_of :hour, :date
end

app/controllers/timecards_controller.rb
class TimecardsController < ApplicationController
  # before_action :set_timecard, only: [:show, :edit, :update, :destroy]
  before_filter :set_member, only: [:show, :index]

  # GET /timecards
  # GET /timecards.json
  def index
    @timecards = @member.timecards.all
  end

  # GET /timecards/1
  # GET /timecards/1.json
  def show
    @timecard = @member.timecards.find(params[:id])
    if @timecard.nil?
      render status: 404, nothing: true and return
    end
  end

  # GET /timecards/new
  def new
    @timecard = LeaveRequest.new
  end

  # POST /timecards
  # POST /timecards.json
  def create
    unless current_user.system?
      render status: 403, nothing: true and return
    end

    @member = Member.find(params[:member_id])
    @timecard = @member.timecards.build(timecard_params)

    if @timecard.save
      render nothing: true, status: :created, location: member_timecard_url(@member, @timecard)
    else
      render status: 400, nothing: true
    end
  end

  private

  def set_member
    @member = Member.find(params[:member_id])
    if @member != current_user && @member.assign != current_user
      render status: 403, nothing: true and return
    end
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  def timecard_params
    params.require(:timecard).permit(:hour, :date)
  end
end

app/helpers/timecards_helper.rb
module TimecardsHelper
end

app/views/timecards/_form.html.erb
<%= form_for(@timecard) do |f| %>
  <% if @timecard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@timecard.errors.count, "error") %> prohibited this timecard from being saved:</h2>

      <ul>
      <% @timecard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/timecards/edit.html.erb
<h1>Editing Timecard</h1>

<%= render 'form' %>

<%= link_to 'Show', @timecard %> |
<%= link_to 'Back', timecards_path %>

app/views/timecards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Timecards</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @timecards.each do |timecard| %>
      <tr>
        <td><%= link_to 'Show', timecard %></td>
        <td><%= link_to 'Edit', edit_timecard_path(timecard) %></td>
        <td><%= link_to 'Destroy', timecard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Timecard', new_timecard_path %>

app/views/timecards/new.html.erb
<h1>New Timecard</h1>

<%= render 'form' %>

<%= link_to 'Back', timecards_path %>

app/views/timecards/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_timecard_path(@timecard) %> |
<%= link_to 'Back', timecards_path %>