config/routes.rb
Rails.application.routes.draw do
  resources :members, only: [:create, :show, :index], defaults: {format: :json} do
    post :login, on: :collection
    post :logout, on: :collection
    post :assigned, on: :member
    resources :leave_requests, only: [:create, :show, :index] do
      post :processed, on: :member
    end
    resources :timecards, only: [:create, :show, :index]
    resources :leave_conflicts, only: [:create, :show, :index]
  end

end

app/models/leave_request.rb
class LeaveRequest
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Enum

  enum :status, [:created, :approved, :rejected], default: :created
  field :title, type: String
  field :from, type: Time
  field :to, type: Time

  embedded_in :member

  validates_presence_of :title, :from, :to
end

app/controllers/leave_requests_controller.rb
class LeaveRequestsController < ApplicationController
  # before_action :set_leave_request, only: [:show, :edit, :update, :destroy]
  before_filter :set_member

  # GET /leave_requests
  # GET /leave_requests.json
  def index
    @leave_requests = @member.leave_requests.all
  end

  # GET /leave_requests/1
  # GET /leave_requests/1.json
  def show
    @leave_request = @member.leave_requests.find(params[:id])
    if @leave_request.nil?
      render status: 404, nothing: true and return
    end
  end

  # GET /leave_requests/new
  def new
    @leave_request = LeaveRequest.new
  end

  def processed
    @leave_request = @member.leave_requests.find(params[:id])
    if @leave_request.nil?
      render status: 404, nothing: true and return
    end

    if current_user != @member.assign
      render status: 403, nothing: true and return
    end

    if params[:approved]
      @leave_request.approved!
    elsif params[:rejected]
      @leave_request.rejected!
    else
      render status: 400, nothing: true and return
    end

    render status: 200, nothing: true
  end

  # POST /leave_requests
  # POST /leave_requests.json
  def create
    @member = Member.find(params[:member_id])
    if @member != current_user
      render status: 403, nothing: true and return
    end
    @leave_request = @member.leave_requests.build(leave_request_params)

    if @leave_request.save
      render :show, status: :created, location: member_leave_request_url(@member, @leave_request)
    else
      render status: 400, nothing: true
    end
  end

  private

  def set_member
    @member = Member.find(params[:member_id])
    if @member != current_user && @member.assign != current_user
      render status: 403, nothing: true and return
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_leave_request
    @leave_request = LeaveRequest.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def leave_request_params
    params.require(:leave_request).permit(:from, :to, :title)
  end
end

app/helpers/leave_requests_helper.rb
module LeaveRequestsHelper
end

app/views/leave_requests/_form.html.erb
<%= form_for(@leave_request) do |f| %>
  <% if @leave_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@leave_request.errors.count, "error") %> prohibited this leave_request from being saved:</h2>

      <ul>
      <% @leave_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leave_requests/edit.html.erb
<h1>Editing Leave Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @leave_request %> |
<%= link_to 'Back', leave_requests_path %>

app/views/leave_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Leave Requests</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leave_requests.each do |leave_request| %>
      <tr>
        <td><%= link_to 'Show', leave_request %></td>
        <td><%= link_to 'Edit', edit_leave_request_path(leave_request) %></td>
        <td><%= link_to 'Destroy', leave_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Leave request', new_leave_request_path %>

app/views/leave_requests/new.html.erb
<h1>New Leave Request</h1>

<%= render 'form' %>

<%= link_to 'Back', leave_requests_path %>

app/views/leave_requests/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_leave_request_path(@leave_request) %> |
<%= link_to 'Back', leave_requests_path %>