config/routes.rb
Rails.application.routes.draw do
  resources :members, only: [:create, :show, :index], defaults: {format: :json} do
    post :login, on: :collection
    post :logout, on: :collection
    post :assigned, on: :member
    resources :leave_requests, only: [:create, :show, :index] do
      post :processed, on: :member
    end
    resources :timecards, only: [:create, :show, :index]
    resources :leave_conflicts, only: [:create, :show, :index]
  end

end

app/models/leave_conflict.rb
class LeaveConflict
  include Mongoid::Document
  include Mongoid::Timestamps
  field :leave_request_id, type: String
  field :timecard_id, type: String

  attr_accessor :leave_request, :timecard

  embedded_in :member

  validates_presence_of :leave_request_id, :timecard_id
end

app/controllers/leave_conflicts_controller.rb
class LeaveConflictsController < ApplicationController
  # before_action :set_leave_conflict, only: [:show, :edit, :update, :destroy]
  before_filter :set_member, only: [:show, :index]

  # GET /leave_conflicts
  # GET /leave_conflicts.json
  def index
    @leave_conflicts = @member.leave_conflicts.map do |leave_conflict|
      request_id = leave_conflict.leave_request_id
      timecard_id = leave_conflict.timecard_id
      leave_conflict.leave_request = @member.leave_requests.find(request_id)
      leave_conflict.timecard = @member.timecards.find(timecard_id)
      leave_conflict
    end
  end

  # GET /leave_conflicts/1
  # GET /leave_conflicts/1.json
  def show
    @leave_conflict = @member.leave_conflicts.find(params[:id])
    if @leave_conflict.nil?
      render status: 404, nothing: true and return
    end
    request_id = @leave_conflict.leave_request_id
    timecard_id = @leave_conflict.timecard_id
    @leave_conflict.leave_request = @member.leave_requests.find(request_id)
    @leave_conflict.timecard = @member.timecards.find(timecard_id)


  end

  # GET /leave_conflicts/new
  def new
    @leave_conflict = LeaveRequest.new
  end

  # POST /leave_conflicts
  # POST /leave_conflicts.json
  def create
    unless current_user.system?
      render status: 403, nothing: true and return
    end

    @member = Member.find(params[:member_id])
    @leave_conflict = @member.leave_conflicts.build(leave_conflict_params)

    if @leave_conflict.save
      render nothing: true, status: :created, location: member_leave_conflict_url(@member, @leave_conflict)
    else
      render status: 400, nothing: true
    end
  end

  private

  def set_member
    @member = Member.find(params[:member_id])
    if @member != current_user && @member.assign != current_user
      render status: 403, nothing: true and return
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def leave_conflict_params
    params.require(:leave_conflict).permit(:leave_request_id, :timecard_id)
  end
end

app/helpers/leave_conflicts_helper.rb
module LeaveConflictsHelper
end

app/views/leave_conflicts/_form.html.erb
<%= form_for(@leave_conflict) do |f| %>
  <% if @leave_conflict.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@leave_conflict.errors.count, "error") %> prohibited this leave_conflict from being saved:</h2>

      <ul>
      <% @leave_conflict.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leave_conflicts/edit.html.erb
<h1>Editing Leave Conflict</h1>

<%= render 'form' %>

<%= link_to 'Show', @leave_conflict %> |
<%= link_to 'Back', leave_conflicts_path %>

app/views/leave_conflicts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Leave Conflicts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leave_conflicts.each do |leave_conflict| %>
      <tr>
        <td><%= link_to 'Show', leave_conflict %></td>
        <td><%= link_to 'Edit', edit_leave_conflict_path(leave_conflict) %></td>
        <td><%= link_to 'Destroy', leave_conflict, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Leave conflict', new_leave_conflict_path %>

app/views/leave_conflicts/new.html.erb
<h1>New Leave Conflict</h1>

<%= render 'form' %>

<%= link_to 'Back', leave_conflicts_path %>

app/views/leave_conflicts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_leave_conflict_path(@leave_conflict) %> |
<%= link_to 'Back', leave_conflicts_path %>